"""fix country column length postgres

Revision ID: 8c45d1dcc75f
Revises: 80fcb721b17f
Create Date: 2026-01-23 23:24:26.835550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c45d1dcc75f'
down_revision: Union[str, None] = '80fcb721b17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airports', 'country',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airports', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
