"""create slots table

Revision ID: 9529b26ead25
Revises: a179e2db0ebb
Create Date: 2026-01-11 20:02:48.497982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9529b26ead25'
down_revision: Union[str, None] = 'a179e2db0ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('runway_id', sa.String(length=36), nullable=False),
    sa.Column('flight_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['runway_id'], ['runways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_airport_id'), 'slots', ['airport_id'], unique=False)
    op.create_index(op.f('ix_slots_flight_id'), 'slots', ['flight_id'], unique=False)
    op.create_index(op.f('ix_slots_runway_id'), 'slots', ['runway_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slots_runway_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_flight_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_airport_id'), table_name='slots')
    op.drop_table('slots')
    # ### end Alembic commands ###
