"""create gates table

Revision ID: 9c4ba0042bef
Revises: c366d4d1505c
Create Date: 2026-01-09 15:46:53.381238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4ba0042bef'
down_revision: Union[str, None] = 'c366d4d1505c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gate_code', sa.String(length=10), nullable=False),
    sa.Column('terminal', sa.String(length=10), nullable=False),
    sa.Column('gate_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_airport_id'), 'gates', ['airport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gates_airport_id'), table_name='gates')
    op.drop_table('gates')
    # ### end Alembic commands ###
