"""create flights table

Revision ID: a451d53d5b05
Revises: 9c4ba0042bef
Create Date: 2026-01-10 13:42:04.701664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a451d53d5b05'
down_revision: Union[str, None] = '9c4ba0042bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('departure_airport_id', sa.String(length=36), nullable=False),
    sa.Column('arrival_airport_id', sa.String(length=36), nullable=False),
    sa.Column('departure_gate_id', sa.String(length=36), nullable=True),
    sa.Column('arrival_gate_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['arrival_gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['departure_gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_arrival_airport_id'), 'flights', ['arrival_airport_id'], unique=False)
    op.create_index(op.f('ix_flights_arrival_gate_id'), 'flights', ['arrival_gate_id'], unique=False)
    op.create_index(op.f('ix_flights_departure_airport_id'), 'flights', ['departure_airport_id'], unique=False)
    op.create_index(op.f('ix_flights_departure_gate_id'), 'flights', ['departure_gate_id'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_departure_gate_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_departure_airport_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_arrival_gate_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_arrival_airport_id'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
